### ISSUE TITLE
implement IVR

### ISSUE THREAD

**Issue by tsearle** [openline-ai/openline-voice#32]
IVR (2 numbers sales and support but same IVR)
Sales (Press 1)
Put on hold after being connected to extension
Support (Press 2)
Voicemail press * (lol what it’s blocked due to too many attempts…)
At tone say your name
Directory (Press 8)
Press digits to try to match to someones name
Can dial extension at any time
Round robins to active users when forwarded to queue

**Comment by gabriel0003** [comment]
Update:
Dial Extension (Press 3)
